[project]
name = "hippocraticai"
version = "0.1.0"
description = "hippocratic_ai takehome"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "environs>=14.1.1",
    "openai>=1.62.0",
]
