[project]
name = "hippocraticai"
version = "0.1.0"
description = "hippocratic_ai takehome"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai>=1.62.0",
    "python-dotenv>=1.0.1",
]
